version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    # container_name: pgadmin-teslo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD : admin
    ports:
      - "80:80"
    depends_on:
      - db
  
# docker-compose up
# docker-compose up -d
# psql -h localhost -p 5432 -U postgres
# docker-compose logs
# ingresar al localhost:80
# esperar ya que pgadmin demora max 10min